apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rglyb580o-go-gitops
  description: This is GitOps manifest for rglyb580o-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rglyb580o-go
    backstage.io/kubernetes-id: rglyb580o-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rglyb580o-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rglyb580o-go
